### ISSUE TITLE
Errors when updating certs.

### ISSUE THREAD

**Issue by mrmurb** [dmp1ce/nginx-proxy-letsencrypt#32]
This docker fails to update certs since a couple of days. Might be because some changes done to nginx-proxy?

Might be worth mentioning on the page if you do not intend to continue developing this image.

All the best! 

```
letsencrypt.1 | Traceback (most recent call last):
letsencrypt.1 |     working_set = WorkingSet._build_master()
letsencrypt.1 |     ws.require(__requires__)
letsencrypt.1 |     needed = self.resolve(parse_requirements(requirements))
letsencrypt.1 |     requirements.extend(dist.requires(req.extras)[::-1])
letsencrypt.1 |     dm = self._dep_map
letsencrypt.1 |   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2597, in _dep_map
letsencrypt.1 |     self.__dep_map = self._compute_dependencies()
letsencrypt.1 |   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2614, in _compute_dependencies
letsencrypt.1 |     from _markerlib import compile as compile_marker
letsencrypt.1 | ImportError: No module named _markerlib
```

**Comment by dmp1ce** [comment]
I'm not planning on maintaining this image. I'll make that known in the README and let anyone take over the repository if they want to.

**Comment by dmp1ce** [comment]
Updated README
